import os

LOG_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "bot_activity.log")

DB_USER = "admin"
DB_PASS = "unknown_vault"
DB_NAME = "market_high_freq"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_URL  = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

SYMBOL         = "BTC/USDT"
EXCHANGE_ID    = "binance"
TF_SNIPER      = "1m"
TF_STRUCTURE   = "15m"
TF_MACRO       = "1h"
CANDLE_LIMIT   = 600

EMA_FAST        = 9
EMA_SLOW        = 21
EMA_TREND       = 200
RSI_PERIOD      = 14
ATR_PERIOD      = 14
ZSCORE_LOOKBACK = 50

SWING_LOOKBACK     = 5
STRUCTURE_LOOKBACK = 20

RSI_OVERSOLD        = 35
RSI_TREND_MIN       = 45
ENTRY_SCORE_MIN     = 2
TRADE_COOLDOWN_BARS = 20

ATR_NOISE_MAX   = 0.45
ADX_MIN_TREND   = 15
ADX_STRONG      = 25

USE_STRUCTURE_LEVELS = True
ATR_SL_MULT          = 2.142
ATR_TP_MULT          = 0.65

SCOUT_RR_MIN    = 1.50
SCOUT_RR_MAX    = 1.75
AMBUSH_RR_MIN   = 1.76
AMBUSH_RR_MAX   = 2.49
UNICORN_RR_MIN  = 2.50
UNICORN_RR_MAX  = 5.00
RR_MIN_REQUIRED = SCOUT_RR_MIN

SCOUT_PROB_MIN  = 66.439
AMBUSH_PROB_MIN = 81.027
UNICORN_PROB_MIN= 88.020

SCOUT_MULT   = 1.0
AMBUSH_MULT  = 1.25
UNICORN_MULT = 3.0

SCOUT_BE_THRESHOLD   = 0.645
AMBUSH_BE_THRESHOLD  = 0.621
UNICORN_BE_THRESHOLD = 0.95

SCOUT_PROFIT_LOCK   = 0.00
AMBUSH_PROFIT_LOCK  = 0.00
UNICORN_PROFIT_LOCK = 0.00

SCOUT_MAX_BARS   = 240
AMBUSH_MAX_BARS  = 360
UNICORN_MAX_BARS = 720

BE_DYNAMIC_THRESHOLD = AMBUSH_BE_THRESHOLD
PROFIT_LOCK_FRACTION = AMBUSH_PROFIT_LOCK
MAX_TRADE_BARS       = AMBUSH_MAX_BARS

INITIAL_CASH       = 10000.0
RISK_PER_TRADE_PCT = 0.02
LEVERAGE           = 20
KELLY_FRACTION     = 0.30
MAX_DRAWDOWN_HALT  = 0.12
DRAWDOWN_REDUCE_1  = 0.04
DRAWDOWN_REDUCE_2  = 0.08

STOP_LOSS_PCT = 0.02

# ── V10.9: PARÁMETROS DINÁMICOS Y SMC ─────────────────────────────────────────
ATR_15M_MAX_PCT        = 0.0035
ATR_COMPRESSION_THRESH = 0.0030

CVD_1M_CONTRA_THRESHOLD = -15_000
CVD_15M_LONG_BLOCK      = -55_000
CVD_15M_SHORT_SUPPORT   = -40_000

EMA_DIST_1H_EXTEND_PCT  = -0.0055
VOL_RATIO_SPIKE_MAX     = 2.0

# ── V10.9: PARÁMETROS EXCLUSIVOS UNICORN ─────────────────────────────────────
UNICORN_CVD15M_BLOCK   = -60_000
UNICORN_CVD15M_ALIGNED = -48_000
UNICORN_RSI_EXTREME    = 30
UNICORN_OB_TOLERANCE   = 0.003

# ── SMC ESTRUCTURA ───────────────────────────────────────────────────────────
FVG_LOOKBACK_1M        = 30
FVG_LOOKBACK_15M       = 50
OB_LOOKBACK            = 100
EQH_EQL_LOOKBACK       = 80
EQH_EQL_TOLERANCE_PCT  = 0.002
BOS_CHOCH_LOOKBACK     = 40